export enum ScanStateEnum {
	NEW = 'NEW',
	RUNNING = 'RUNNING',
	PENDING = 'PENDING',
	INGESTING = 'INGESTING',
	DONE = 'DONE',
	CANCELING = 'CANCELING',
	CANCELED = 'CANCELED',
	FAILED = 'FAILED',
}
